In [1]:
import numpy as np

In [2]:
he = np.load("../data/hand_eye/hand_eye.npz")

In [3]:
he["r_cam2gripper"]

array([[ 0.01950565,  0.99979981, -0.0044581 ],
       [-0.02284127, -0.00401217, -0.99973105],
       [-0.9995488 ,  0.01960223,  0.02275844]])

In [4]:
he["t_cam2gripper"]

array([[-0.0009276 ],
       [-0.02246503],
       [ 0.05411597]])

In [5]:
he1 = np.load("../data/hand_eye/h.npy")

In [6]:
he1

array([[ 0.06784204,  0.99586424, -0.06043077,  0.15887888],
       [ 0.01375423, -0.06149811, -0.99801243,  0.5763202 ],
       [-0.99760126,  0.06687602, -0.0178695 ,  0.13902047],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [9]:
poses = np.load("../data/hand_eye/poses.npy")

In [10]:
len(frames)

985