In [1]:
import numpy as np

In [4]:
dist = np.load("../data/intrinsics/dist.npy")
dist

array([[ 4.23236064e-02,  4.52591853e-01,  1.06242035e-03,
        -5.32237086e-04, -1.64887082e+00]])

In [5]:
mtx = np.load("../data/intrinsics/mtx.npy")
mtx

array([[571.53917026,   0.        , 328.13762744],
       [  0.        , 571.05910814, 245.30183519],
       [  0.        ,   0.        ,   1.        ]])

In [7]:
data = np.load("../data/intrinsics/intrinsics.npz")

In [9]:
data["mtx"], data["dist"]

(array([[574.01870681,   0.        , 328.90797846],
        [  0.        , 573.7619472 , 243.81421652],
        [  0.        ,   0.        ,   1.        ]]),
 array([[ 3.10334662e-02,  6.15702392e-01,  8.31168943e-04,
         -3.26508230e-04, -2.21216690e+00]]))